version: '3'

tasks:
  release:
    cmds:
      - git tag v{{.CLI_ARGS}}
      - jq '.version="{{.CLI_ARGS}}"' package.json > package.json.tmp
      - rm package.json
      - mv package.json.tmp package.json
      - task: cl-new
        vars: {VERSION: "{{.CLI_ARGS}}"}
      - git add package.json CHANGELOG.md
      - git commit -am "release: v{{.CLI_ARGS}}"

  cl-new:
    cmds:
      - changeloguru g --version {{.VERSION}} --to {{.PREV_TAG}}
    vars:
      PREV_TAG:
        sh: git describe --abbrev=0 --tags --exclude="$(git describe --abbrev=0 --tags)" "$(git describe --abbrev=0 --tags)"