version: '3'

tasks:
  cl-new:
    cmds:
      - changeloguru g --version {{.CURRET_TAG}} --to {{.PREV_TAG}}
    silent: true
    vars:
      CURRET_TAG:
        sh: git describe --tags $(git rev-list --tags --max-count=1)
      PREV_TAG:
        sh: git describe --abbrev=0 --tags --exclude="$(git describe --abbrev=0 --tags)" "$(git describe --abbrev=0 --tags)"