name: Build deno
 
on:
  - push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
      - run: deno -V
      - run: deno check src/index.ts